name: xplore
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.12.0 <4.0.0"
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^6.6.0
  collection: ^1.17.2
  cupertino_icons: ^1.0.2
  dotted_border: ^3.1.0
  firebase_auth: ^6.5.4
  firebase_core: ^4.11.0
  firebase_database: ^12.4.3
  firebase_storage: ^13.4.3
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.1
  flutter_gemini: ^3.0.0
  flutter_svg: ^2.0.9
  freezed_annotation: ^3.1.0
  geolocator: ^14.0.3
  google_maps_flutter: ^2.5.3
  google_maps_flutter_ios_sdk10: ^2.18.4
  google_sign_in: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image: ^4.8.0
  image_picker: ^1.0.7
  json_annotation: ^4.12.0
  logger: ^2.2.0
  path_provider: ^2.1.2
  photo_view: ^0.15.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.2.5
  build_runner: ^2.15.0
  json_serializable: ^6.14.0
  firebase_auth_mocks: ^0.15.2
  fake_cloud_firestore: ^4.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/placeholders/
    - assets/icons/
    - assets/demo/
    - assets/maps/
    - assets/illustrations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
