// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPEHREqi5JRNRoDoXLd_nEwQ7PtsaV3S8',
    appId: '1:700905798457:web:43c948ca007d10b0c446e8',
    messagingSenderId: '700905798457',
    projectId: 'xplore-a7012',
    authDomain: 'xplore-a7012.firebaseapp.com',
    storageBucket: 'xplore-a7012.appspot.com',
    measurementId: 'G-B8LMLQN0YZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB27ylyaeWyCqOjTsbsJDVcKAa6ulcbZDo',
    appId: '1:700905798457:android:930ce25b85bc71a6c446e8',
    messagingSenderId: '700905798457',
    projectId: 'xplore-a7012',
    storageBucket: 'xplore-a7012.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2Lx8CwK1NQT7Z3B9-2MpG3GOXBELX-cQ',
    appId: '1:700905798457:ios:40f4626fde9bbde4c446e8',
    messagingSenderId: '700905798457',
    projectId: 'xplore-a7012',
    storageBucket: 'xplore-a7012.appspot.com',
    iosBundleId: 'com.example.xplore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2Lx8CwK1NQT7Z3B9-2MpG3GOXBELX-cQ',
    appId: '1:700905798457:ios:2e0c536d91772786c446e8',
    messagingSenderId: '700905798457',
    projectId: 'xplore-a7012',
    storageBucket: 'xplore-a7012.appspot.com',
    iosBundleId: 'com.example.xplore.RunnerTests',
  );
}
